# Generated by Django 6.0.3 on 2026-03-26 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_itinerarydrafts_return_flight_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRoles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_roles',
            },
        ),
        migrations.CreateModel(
            name='AdminUsers',
            fields=[
                ('admin_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('password_hash', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_users', to='api.adminroles')),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
        migrations.CreateModel(
            name='AdminAuditLogs',
            fields=[
                ('audit_log_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=120)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(default='success', max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=64, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.adminroles')),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='audit_logs', to='api.adminusers')),
            ],
            options={
                'db_table': 'admin_audit_logs',
            },
        ),
    ]
