# Generated by Django 6.0.3 on 2026-03-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adminroles_adminusers_adminauditlogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSearchCache',
            fields=[
                ('cache_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider_type', models.CharField(max_length=20)),
                ('cache_key', models.CharField(max_length=255, unique=True)),
                ('request_signature', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField()),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provider_search_cache',
                'indexes': [models.Index(fields=['provider_type', 'expires_at'], name='provider_se_provide_cd7dc6_idx'), models.Index(fields=['cache_key'], name='provider_se_cache_k_1ef852_idx')],
            },
        ),
    ]
