from django.urls import path
from . import views

urlpatterns = [
    path('flights/', views.get_flights, name='get_flights'),
    path('flights/search', views.search_flights, name='search_flights'),
    path('flight-locations/', views.get_flight_locations, name='get_flight_locations'),
    path('flight-routes/', views.get_flight_routes, name='get_flight_routes'),
    path('hotels/', views.get_hotels, name='get_hotels'),
    path('hotels/search', views.search_hotels, name='search_hotels'),
    path('hotels/offers', views.hotel_offer_lookup, name='hotel_offer_lookup'),
    path('cars/', views.get_cars, name='get_cars'),
    path('cars/search', views.search_cars, name='search_cars'),
    path('bookings/', views.get_bookings, name='get_bookings'),
    path('bookings/<str:reference>/', views.retrieve_booking, name='retrieve_booking'),
    path('countries/', views.get_countries, name='get_countries'),
    path('chat', views.ai_chat, name='ai_chat'),
    path('planner/sessions/', views.planner_sessions, name='planner_sessions'),
    path('planner/sessions/<int:session_id>/', views.planner_session_detail, name='planner_session_detail'),
    path('planner/sessions/<int:session_id>/messages/', views.planner_session_message, name='planner_session_message'),
    path('planner/sessions/<int:session_id>/plan/', views.planner_session_plan, name='planner_session_plan'),
    path('planner/sessions/<int:session_id>/drafts/<int:draft_id>/', views.planner_draft_update, name='planner_draft_update'),
    path('planner/sessions/<int:session_id>/drafts/<int:draft_id>/enrich/', views.planner_draft_enrich, name='planner_draft_enrich'),
    path('planner/sessions/<int:session_id>/drafts/<int:draft_id>/revalidate/', views.planner_draft_revalidate, name='planner_draft_revalidate'),
    path('planner/provider-status/', views.provider_status, name='provider_status'),
    path('health/', views.health_status, name='health_status'),
    path('ready/', views.readiness_status, name='readiness_status'),
    path('auth/register/', views.register_customer, name='register_customer'),
    path('auth/login/', views.login_customer, name='login_customer'),
    path('auth/account/<int:customer_id>/', views.customer_account, name='customer_account'),
    path('admin/auth/login/', views.admin_login, name='admin_login'),
    path('admin/auth/session/', views.admin_session, name='admin_session'),
    path('admin/roles/', views.admin_roles, name='admin_roles'),
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/bookings/', views.admin_bookings, name='admin_bookings'),
    path('admin/bookings/<int:booking_id>/status/', views.admin_booking_status, name='admin_booking_status'),
    path('admin/flights/', views.admin_flights, name='admin_flights'),
    path('admin/flights/<int:flight_id>/', views.admin_flight_detail, name='admin_flight_detail'),
    path('admin/hotels/', views.admin_hotels, name='admin_hotels'),
    path('admin/hotels/<int:hotel_id>/', views.admin_hotel_detail, name='admin_hotel_detail'),
    path('admin/cars/', views.admin_cars, name='admin_cars'),
    path('admin/cars/<int:car_id>/', views.admin_car_detail, name='admin_car_detail'),
    path('', views.api_root, name='api_root'),
]
